[package]
name = "hipster-stack-2019"
version = "0.1.0"
authors = ["Fredrik Ekholdt <freekh@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "1.0.0-beta.4"
